package com.example.healthcare.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.Data;

@Document(collection = "appointments")
@Data
public class Appointment {
    @Id
    private String id;
    private String firstName;
    private String lastName;
    private String phone;
    private String email;
    private String date;
    private String startTime;
    private String endTime;
    private String problemDescription;
    private String doctorName;

    // Constructors, getters, and setters can be automatically generated by Lombok
}
