package com.example.healthcare.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.Data;

@Document(collection = "registrations")
@Data
public class Registration {
    @Id
    private String id;
    private String firstName;
    private String lastName;
    private String phone;
    private String email;
    private String password;

    // Constructors, getters, and setters can be automatically generated by Lombok
}
